# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5a62a1790678e01d1bb6e5eff8c835dda64a17663304aec12dc75a3d4627d7ecf8717193f7e02d6e49f93b790f3309051c33facfae5bc962cd75e09d5583e6

test:
  secret_key_base: 3894f37954f8f0fcdd838de3a328a97825cc59926c56fa62dfd0e9aee8d7a499e2ec7c5d83798a461a597f201ba35e49a959a8e37714c350f87fc203e2fd4f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
